# Generated by Django 5.1.6 on 2025-05-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='firebase_url',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(default='uploads/dummy.txt', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
