# Generated by Django 5.1.6 on 2025-05-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filemanager', '0002_remove_uploadedfile_firebase_url_uploadedfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='user_id',
            field=models.CharField(default='uploads/dummy.txt', max_length=100),
            preserve_default=False,
        ),
    ]
